[package]
name = "gunnir"
version = "0.1.0"
edition = "2024"

[dependencies]
gunnir-board = { path = "gunnir-board" }
rand = { version = "0.9.2", features = ["small_rng"] }
rustyline = "17.0.0"

[workspace]
resolver = "3"
members = ["gunnir-board", "gunnir-common"]
